version: 2.1
jobs:   
  build:
    docker:
      - image: alpine:3.7
    steps:
      - run: # print the name of the branch we're on
          name: "What branch am I on?"
          command: echo ${CIRCLE_BRANCH}
      - run: # print the name of the branch we're on
          name: "What is the las commit sha?"
          command: echo ${CIRCLE_SHA1}
      - run:
          name: Install Docker client
          command: apk add docker-cli
      - run: docker build -t company/app:$CIRCLE_BRANCH .
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'    
