version: 2.1
jobs:
  prebuild:
    working_directory: ~/Imagen
    machine: # executor type
      image: ubuntu-1604:201903-01 # # recommended linux image - includes Ubuntu 16.04, docker 18.09.3, docker-compose 1.23.1
    steps:
      - checkout
      - run:
          name: "Crear imagen docker"
          command: |
            $(aws ecr get-login --no-include-email --region us-west-2)
            cd Imagen
            cat Dockerfile
            echo ${CIRCLE_SHA1}
            docker build -t nginx-elmer-trambo:${CIRCLE_SHA1} .
            docker images
            docker tag nginx-elmer-trambo:${CIRCLE_SHA1} $Uri_ECR:${CIRCLE_SHA1}
            docker push $Uri_ECR:${CIRCLE_SHA1}
            aws ecs register-task-definition --family nuevaTask --container-definitions "[{\"name\":\"Nginx-Service\",\"portMappings\":[{\"hostPort\":80,\"protocol\":\"tcp\",\"containerPort\":80}],\"image\":\"$Uri_ECR:${CIRCLE_SHA1}\",\"cpu\":10,\"memory\":300,\"essential\":true}]"
            aws ecs list-task-definitions
            aws ecs update-service --cluster $ClusterName --service $ServiceName --task-definition nuevaTask --health-check-grace-period-seconds 0
            aws ecs update-service --force-new-deployment --cluster $ClusterName --service $ServiceName
workflows:
  version: 2
  build_and_test:
    jobs:
      - prebuild