version: 2.1
jobs:
  prueba:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run: # print the name of the branch we're on
          name: "Hola?"
          command: echo ${CIRCLE_BRANCH}
  build:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run: # print the name of the branch we're on
          name: "What branch am I on?"
          command: echo ${CIRCLE_BRANCH}
      - run: # print the name of the branch we're on
          name: "What is the las commit sha?"
          command: echo ${CIRCLE_SHA1}
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
workflows:
  version: 2
  build_and_test:
    jobs:
      - prueba
      - build