version: 2.1
jobs:
  prebuild:
    working_directory: ~/Imagen
    machine: # executor type
      image: ubuntu-1604:201903-01 # # recommended linux image - includes Ubuntu 16.04, docker 18.09.3, docker-compose 1.23.1
    steps:
      - checkout
      - run:
          name: "Crear imagen docker"
          command: |
            $(aws ecr get-login --no-include-email --region us-west-2)
            aws s3 ls
            cd Imagen
            cat Dockerfile
            echo ${CIRCLE_SHA1}
            docker build -t nginx-elmer-trambo:${CIRCLE_SHA1} .
            docker images
            docker tag nginx-elmer-trambo:${CIRCLE_SHA1} 492266378106.dkr.ecr.us-west-2.amazonaws.com/nginx-elmer-trambo:${CIRCLE_SHA1}
            docker push 492266378106.dkr.ecr.us-west-2.amazonaws.com/nginx-elmer-trambo:${CIRCLE_SHA1}
            docker --version
            echo " 
            {
              "containerDefinitions": [
                {
                  "name": "task${CIRCLE_SHA1}",
                  "image": "busybox",
                  "cpu": 10,
                  "command": [
                    "sleep",
                    "360"
                  ],
                  "memory": 10,
                  "essential": true
                }
              ],
              "family": "sleep360"
            }" >> ejemplo.json"
            echo "+++++++++++++++++++++++++++++++++++++++"
            cat ejemplo.json
  build:
    docker:
      - image: alpine:3.7
    steps:
      - checkout
      - run: # print the name of the branch we're on
          name: "What branch am I on?"
          command: echo ${CIRCLE_BRANCH}
      - run: # print the name of the branch we're on
          name: "What is the las commit sha?"
          command: echo ${CIRCLE_SHA1}
      - run:
          name: The First Step
          command: |
            echo 'Hello World!'
            echo 'This is the delivery pipeline'
workflows:
  version: 2
  build_and_test:
    jobs:
      - prebuild
      - build:
          requires:
            - prebuild